# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'rake docusign_rest:generate_config' as many times as you need
# to replace the content of this file with a new config.

require 'docusign_rest'

DocusignRest.configure do |config|
  config.username       = 'mottet.julien123@gmail.com'
  config.password       = 'Blink182'
  config.integrator_key = '07f3f7a8-5a73-4f3d-8917-aa7ba622fff0'
  config.account_id     = '6396016'
  #config.endpoint       = 'https://www.docusign.net/restapi'
  #config.api_version    = 'v2'
  config.open_timeout   = 2 # default value is 5
  config.read_timeout   = 5 # default value is 10
end

